[package]
name = "cstrml-swork"
version = "1.0.0"
authors = ["crustio"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://crust.network"
repository = "https://github.com/paritytech/crust/"

[dependencies]
# third party dependencies
codec = { default-features = false, package = "parity-scale-codec", version = "3.0.0" }
serde = { optional = true, version = "1.0.116" }
base64 = { default-features = false, features = ["alloc"], version = "0.12.2" }
p256 = { default-features = false, features = ["ecdsa"], version = "0.5.1" }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }

# substrate frame dependencies
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }

# substrate primitives
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }
sp-io = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }

# crust runtime modules
primitives = { package = "crust-parachain-primitives", path = "../../primitives", default-features = false }
webpki = { package = "webpki", path = "../../../utils/webpki", default-features = false }
serde_json = { package = "serde_json_no_std", path = "../../../utils/serde_json_no_std", default-features = false, features = ["alloc"] }

[dev-dependencies]
keyring = { package = "sp-keyring", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.19" }
balances = { package = 'pallet-balances', git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.19" }
primitives = { package = "crust-parachain-primitives", path = "../../primitives", features = ["test"] }
hex = "0.4.2"

[features]
default = ["std"]
std = [
    "serde",
    "codec/std",
    "frame-support/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "frame-system/std",
    "primitives/std",
    "webpki/std"
]